{
 "title": "Speedtest",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Aktuelle Werte", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connection Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gateway_wan_connection_uptime_seconds"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(gateway_wan_bytes_received[$__range])",
     "legendFormat": "Bytes received"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(gateway_wan_bytes_sent[$__range])",
     "legendFormat": "Bytes Sent"
    }
   ]
  },
  {
   "title": "Current Downstream",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_downstream", "legendFormat": "Downstream" }
   ]
  },
  {
   "title": "Current Upstream",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_upstream", "legendFormat": "Upstream" }
   ]
  },
  { "title": "Historische Werte", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Bytes Transfered",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(gateway_wan_bytes_received[$__range])",
     "legendFormat": "Bytes received"
    },
    {
     "expr": "increase(gateway_wan_bytes_sent[$__range])",
     "legendFormat": "Bytes Sent"
    }
   ]
  },
  {
   "title": "Downstream",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "gateway_wan_layer1_downstream_max_bitrate",
     "legendFormat": "Max  Downstream"
    },
    { "expr": "speedtest_downstream", "legendFormat": "Current Downstream" }
   ]
  },
  {
   "title": "Upstream",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "gateway_wan_layer1_upstream_max_bitrate",
     "legendFormat": "Max  Upstream"
    },
    { "expr": "speedtest_upstream", "legendFormat": "Upstream" }
   ]
  },
  {
   "title": "Connection Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gateway_wan_connection_status", "legendFormat": "Connection Status" }
   ]
  },
  {
   "title": "Latenz",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "speedtest_ping", "legendFormat": "Latenz" }
   ]
  }
 ]
}