- name: Ensure speedtest apt key exists
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 379CE192D401AB61
    state: present
- name: Ensure speedtest repository exists
  become: yes
  apt_repository:
    repo: deb https://ookla.bintray.com/debian bionic main
    filename: speedtest
    update_cache: yes
    state: present
- name: Ensure speedtest is installed
  become: yes
  apt:
    name: speedtest
    state: present
- name: Ensure speedtest crontab exists
  cron:
    name: "speedtest"
    job: speedtest --format=csv | awk -F "\"*,\"*" '{print "speedtest_ping "$3"\nspeedtest_downstream "$6*8"\nspeedtest_upstream "$7*8}' | curl --data-binary @- http://localhost:9091/metrics/job/speedtest/instance/smartpi
- name: Ensure speedtest dashboard exists
  become: yes
  copy:
    src: templates/speedtest-dashboard.json
    dest: /var/lib/grafana/dashboards/speedtest-dashboard.json
- name: Ensure fritzbox-target.json exists
  become: yes
  template:
    src: templates/fritzbox-target.json
    dest: /etc/prometheus/targets/fritzbox-target.json
- name: Ensure fritzbox_exporter binary is present
  become: yes
  get_url:
    url: https://github.com/danielr1996/fritzbox_exporter/releases/download/v2.0/fritzbox_exporter-linux-armv6l
    dest: /usr/local/bin/fritzbox_exporter
    mode: '0777'
- name: Ensure fritzbox exporter systemd service exists
  become: yes
  template:
    src: templates/fritzbox_exporter.service
    dest: /etc/systemd/system/fritzbox_exporter.service
- name: Ensure fritzbox_exporter service is started
  become: yes
  systemd:
    state: started
    name: fritzbox_exporter
    daemon_reload: yes