global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'push_gateway'
    honor_labels: true
    static_configs:
      - targets: ["localhost:9091"]
  - job_name: 'filesd'
    file_sd_configs:
      - files: ["targets/*.json"]