{
 "title": "OhmGraphite Prometheus",
 "description": "A prometheus dashboard for viewing sensor data exported by OhmGraphite",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "hardtemp",
    "query": "{__name__=~\"ohm_.*\"}"
   },
   {
    "name": "instance",
    "query": "{__name__=~\"ohm_.*\"}"
   },
   { "name": "network", "query": "ohm_nic_bytes_per_second" },
   {
    "name": "volts",
    "query": "{__name__=~\"ohm_.*\"}"
   },
   {
    "name": "power",
    "query": "{__name__=~\"ohm_.*\"}"
   },
   {
    "name": "fans",
    "query": "{__name__=~\"ohm_.*\"}"
   },
   {
    "name": "control",
    "query": "{__name__=~\"ohm_.*\"}"
   }
  ]
 },
 "panels": [
  { "title": "Load Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_cpu_load_percent{instance=\"$instance\",sensor=\"CPU Total\"}"
    }
   ]
  },
  {
   "title": "RAM Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_ram_load_percent{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_gpunvidia_load_percent{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    },
    {
     "expr": "ohm_gpuati_load_percent{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_hdd_load_percent{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Load Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ohm_cpu_load_percent{instance=\"$instance\",sensor!=\"CPU Total\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ohm_gpunvidia_load_percent{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    },
    {
     "expr": "ohm_gpuati_load_percent{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "ohm_ram_bytes{instance=\"$instance\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "GPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "ohm_gpunvidia_bytes{instance=\"$instance\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "ohm_gpuati_bytes{instance=\"$instance\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    }
   ]
  },
  { "title": "Watts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "$power Wattage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "repeat": "power",
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ohm_${power}_watts{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "$power Wattage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ohm_${power}_watts{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "$hardtemp Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "repeat": "hardtemp",
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ohm_${hardtemp}_celsius{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "$hardtemp Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ohm_${hardtemp}_celsius{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "$hardtemp Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ohm_${hardtemp}_celsius{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "$hardtemp Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ohm_${hardtemp}_celsius{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Volts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "$volts volts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "repeat": "volts",
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ohm_${volts}_volts{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "$volts volts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ohm_${volts}_volts{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Network Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "$network Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "repeat": "network",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ohm_nic_bytes_per_second{instance=\"$instance\",hardware=~\"$network\",sensor=\"Download Speed\"}",
     "legendFormat": "Download"
    },
    {
     "expr": "ohm_nic_bytes_per_second{instance=\"$instance\",hardware=~\"$network\",sensor=\"Upload Speed\"}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "$network Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ohm_nic_bytes_per_second{instance=\"$instance\",hardware=~\"$network\",sensor=\"Download Speed\"}",
     "legendFormat": "Download"
    },
    {
     "expr": "ohm_nic_bytes_per_second{instance=\"$instance\",hardware=~\"$network\",sensor=\"Upload Speed\"}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "$network Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ohm_nic_bytes_per_second{instance=\"$instance\",hardware=~\"$network\",sensor=\"Download Speed\"}",
     "legendFormat": "Download"
    },
    {
     "expr": "ohm_nic_bytes_per_second{instance=\"$instance\",hardware=~\"$network\",sensor=\"Upload Speed\"}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "$network Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ohm_nic_bytes_per_second{instance=\"$instance\",hardware=~\"$network\",sensor=\"Download Speed\"}",
     "legendFormat": "Download"
    },
    {
     "expr": "ohm_nic_bytes_per_second{instance=\"$instance\",hardware=~\"$network\",sensor=\"Upload Speed\"}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "$network Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ohm_nic_bytes_per_second{instance=\"$instance\",hardware=~\"$network\",sensor=\"Download Speed\"}",
     "legendFormat": "Download"
    },
    {
     "expr": "ohm_nic_bytes_per_second{instance=\"$instance\",hardware=~\"$network\",sensor=\"Upload Speed\"}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "$network Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ohm_nic_bytes_per_second{instance=\"$instance\",hardware=~\"$network\",sensor=\"Download Speed\"}",
     "legendFormat": "Download"
    },
    {
     "expr": "ohm_nic_bytes_per_second{instance=\"$instance\",hardware=~\"$network\",sensor=\"Upload Speed\"}",
     "legendFormat": "Upload"
    }
   ]
  },
  { "title": "Fan RPM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "$fans Fan RPM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "repeat": "fans",
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "ohm_${fans}_revolutions_per_minute{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Control", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "$control Control",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 78 },
   "repeat": "control",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ohm_${control}_control_percent{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "$control Control",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ohm_${control}_control_percent{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Frequencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "CPU Frequencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 86 },
   "repeat": "cpu",
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "ohm_cpu_hertz{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "GPU Frequencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "ohm_gpunvidia_hertz{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    },
    {
     "expr": "ohm_gpuati_hertz{instance=\"$instance\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  }
 ]
}